my_duckdbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'analytics.duckdb'
      threads: 4
      schema: main
    prod:
      type: duckdb
      path: 'analytics_prod.duckdb'
      threads: 4
      schema: main
